apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init
  namespace: threetier-app
data:
  mongo-init.js: |
    db = db.getSiblingDB(process.env.MONGO_APP_DB);
    db.createUser({
      user: process.env.MONGO_APP_USER,
      pwd: process.env.MONGO_APP_PASSWORD,
      roles: [{ role: "readWrite", db: process.env.MONGO_APP_DB }]
    });